### ISSUE TITLE
Fix start date of Members of the 19th Bundestag

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/position_statements#14]
These were entered with a start date of the election (24th September), but they don't take office until the constituting meeting (24th October).

We need to run a bulk update to correct these dates (as User:Lucyfediachambers)

**Comment by jacksonj04** [comment]
Based on the [query](https://query.wikidata.org/#SELECT%20%3FitemLabel%20%3Fitem%20%3Fstatement%20%3Fstart%20WHERE%20%7B%0A%20%20%3Fitem%20p%3AP39%20%3Fstatement.%0A%20%20%3Fstatement%20pq%3AP580%20%3Fstart.%0A%20%20%3Fstatement%20pq%3AP2937%20wd%3AQ30579723%20.%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22es%2Cen%22.%20%7D%0A%7D):

```
SELECT ?itemLabel ?item ?statement ?start WHERE {
  ?item p:P39 ?statement.
  ?statement pq:P580 ?start.
  ?statement pq:P2937 wd:Q30579723 .
  SERVICE wikibase:label { bd:serviceParam wikibase:language "es,en". }
}
```

where `Q30579723` is [19th German Bundestag](https://www.wikidata.org/wiki/Q30579723) there are 706 people to be targeted for updating the `P580` 'start date' to `+2017-10-24T00:00:00Z/11`

**Comment by jacksonj04** [comment]
[Done](https://query.wikidata.org/#SELECT%20%3FitemLabel%20%3Fitem%20%3Fstatement%20%3Fstart%20WHERE%20%7B%0A%20%20%3Fitem%20p%3AP39%20%3Fstatement.%0A%20%20%3Fstatement%20pq%3AP580%20%3Fstart.%0A%20%20%3Fstatement%20pq%3AP2937%20wd%3AQ30579723%20.%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22es%2Cen%22.%20%7D%0A%7D)

**Comment by tmtmtmtm** [comment]
Woot! Thanks @jacksonj04
