### ISSUE TITLE
Validate input

### ISSUE THREAD

**Issue by chrismytton** [everypolitician/position_statements#2]
At the moment we just blindly accept any input that the user gives us. We should do some basic checks on it, e.g. that items are in the format `Q\d+`, properties are `P\d+` etc.

**Comment by tmtmtmtm** [comment]
What do you think of explicitly *only* accepting `P39` rather than `P\d+`?

**Comment by chrismytton** [comment]
@tmtmtmtm We'll still want to accept other properties for qualifiers, of course, but I think for the top level claim restricting to P39s is a very sensible idea.
